name: Deploy FastAPI App

on:
  push:
    branches:
      - main  # Trigger on merge to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Pulls the latest changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match your FastAPI project version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and Run Docker Container
        run: |
          docker build -t fastapi-app .
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker run -d -p 8000:8000 --name fastapi-app fastapi-app

      - name: Restart Nginx
        run: sudo systemctl restart nginx

